### ISSUE TITLE
Error using Close menu item

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#127]
**[reported by Chris Barker]** _[Trac time 20070224 115512Z]_ closing a file returns the error:

```
Traceback (most recent call last):
  File "/Users/cbarker/PythonStuff/Peppy/peppy/menu.py", line 140, in OnMenuSelected
    self.action()
  File "/Users/cbarker/PythonStuff/Peppy/peppy/main.py", line 111, in action
    self.frame.close()
  File "/Users/cbarker/PythonStuff/Peppy/peppy/buffers.py", line 573, in close
    if self.app.close(buffer):
  File "/Users/cbarker/PythonStuff/Peppy/peppy/buffers.py", line 731, in close
    buffer.removeAllViews()
  File "/Users/cbarker/PythonStuff/Peppy/peppy/buffers.py", line 165, in removeAllViews
    viewer.frame.closeViewer(viewer)
AttributeError: 'BufferFrame' object has no attribute 'closeViewer'
```

**Comment by robmcmullen** [comment]
_[Trac time 20070224 150529Z]_ 341b9c850233797d6bdd9d166931e4e2f82d7e4c Fixed #127:
- added closeTab to MyNotebook
- buffer removeAllViews now calls the correct method
- BufferApp.close should only call removeAllViews and let it do the work
- fixed various menu problems related to the possibility that there are no active views in the tab
