### ISSUE TITLE
Cancelling a quit closes the window anyway

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#311]
_[Trac time 20071114 235051Z]_ Don Dwiggins reported this on windows:

```
Traceback (most recent call last):
 File "c:\Dwig\Sandbox\peppy\peppy\frame.py", line 356, in OnClose
   wx.GetApp().quit()
 File "c:\Dwig\Sandbox\peppy\peppy\main.py", line 698, in quit
   doit=self.quitHook()
 File "c:\Dwig\Sandbox\peppy\peppy\main.py", line 712, in quitHook
   if not BufferList.promptUnsaved():
 File "c:\Dwig\Sandbox\peppy\peppy\buffers.py", line 59, in promptUnsaved
   dlg.Destroy()
 File
"C:\ProgramFiles\Python24\lib\site-packages\wx-2.8-msw-ansi\wx\_core.py",
line 14033, in __getattr__
   raise PyDeadObjectError(self.attrStr % self._name)
wx._core.PyDeadObjectError: The C++ part of the QuitDialog object has
been deleted, attribute access no longer allowed.
```

> I think I've found the cause of the traceback problem on exit: after you do either of the above procedures, exit peppy by using the close box on the window.  It seems to be a problem in dealing with a "dirty" buffer during shutdown.

**Comment by robmcmullen** [comment]
_[Trac time 20071115 043605Z]_ 8d93f810123e77265dcb646b3064ec166c04d7bb Fixed #311: don't close the window before putting up the quit dialog, because the user could cancel
