### ISSUE TITLE
Crash on first start-up

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#348]
**[reported by Chris Barker]** _[Trac time 20080130 065823Z]_ I just tried starting up Peppy for the first time under Linux The main Frame came up, but did not get painted, and the app hung, with this traceback:

Traceback (most recent call last):
  File "/home/cbarker/Python/peppy/peppy/frame.py", line 424, in OnIdle
    mode.idleHandler()
AttributeError: 'NoneType' object has no attribute 'idleHandler'
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 13826, in <lambda>
    lambda event: event.callable(_event.args, *_event.kw) )
  File "/home/cbarker/Python/peppy/peppy/frame.py", line 611, in titleBuffer
    self.open(wx.GetApp().classprefs.title_page)
  File "/home/cbarker/Python/peppy/peppy/frame.py", line 670, in open
    self.tabs.newBuffer(user_url, buffer, modecls, mode_to_replace)
  File "/home/cbarker/Python/peppy/peppy/frame.py", line 245, in newBuffer
    self.updateWrapper(wrapper)
  File "/home/cbarker/Python/peppy/peppy/frame.py", line 195, in updateWrapper
    self.frame.switchMode()
  File "/home/cbarker/Python/peppy/peppy/frame.py", line 776, in switchMode
    self.setMenumap(mode)
  File "/home/cbarker/Python/peppy/peppy/frame.py", line 489, in setMenumap
    keymap = self.menumap.updateActions(self.show_toolbar)
  File "/home/cbarker/Python/peppy/peppy/menu.py", line 975, in updateActions
    self.updateMenuActions(self.frame.GetMenuBar())
  File "/home/cbarker/Python/peppy/peppy/menu.py", line 897, in updateMenuActions
    action.insertIntoMenu(menu)
  File "/home/cbarker/Python/peppy/peppy/menu.py", line 340, in insertIntoMenu
    self._insertItems(menu,pos,is_toplevel)
  File "/home/cbarker/Python/peppy/peppy/menu.py", line 343, in _insertItems
    items = self.getItems()
  File "/home/cbarker/Python/peppy/peppy/menu.py", line 613, in getItems
    return [str(item) for item in self.storage]
TypeError: 'NoneType' object is not iterable

Then, When I tried to close the Frame, I got:

Traceback (most recent call last):
  File "/home/cbarker/Python/peppy/peppy/frame.py", line 438, in OnClose
    close = wx.GetApp().quit()
  File "/home/cbarker/Python/peppy/peppy/main.py", line 736, in quit
    doit=self.quitHook()
  File "/home/cbarker/Python/peppy/peppy/main.py", line 761, in quitHook
    text = os.linesep().join([str(e) for e in exceptions])
TypeError: 'str' object is not callable

I ended up killing it with xkill, then starting it again, and all seems fine. Maybe it's cause there is a prefs file or something missing the first time?

By the way, I got very similar behavior under windows too.

**Comment by robmcmullen** [comment]
_[Trac time 20080201 210851Z]_ Aha, indeed it seems as if it can't handle a non-existent preferences directory.  That didn't use to be the case, so I'll see what's changed.

**Comment by robmcmullen** [comment]
_[Trac time 20080201 214735Z]_ 493dc20ae9b7e792b01554fbabbc6f3386dbc03e Fixes #348: Forgot to update storage when recent file list didn't exist
