### ISSUE TITLE
URL Minibuffer broken on unicode pathnames

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#362]
_[Trac time 20080208 191828Z]_ Attempting to open a pathname with a unicode component in the URL minibuffer results in:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy-git/peppy/lib/textctrl_autocomplete.py", line 155, in onEnteredText
    self._entryCallback()
  File "/home/rob/src/peppy-git/peppy/mainmenu.py", line 111, in setDynamicChoices
    CompletionMinibuffer.setDynamicChoices(self)
  File "/home/rob/src/peppy-git/peppy/actions/minibuffer.py", line 268, in setDynamicChoices
    choices = self.complete(text)
  File "/home/rob/src/peppy-git/peppy/mainmenu.py", line 122, in complete
    for path in glob.glob(text+"*"):
  File "/usr/lib64/python2.5/glob.py", line 15, in glob
    return list(iglob(pathname))
  File "/usr/lib64/python2.5/glob.py", line 42, in iglob
    yield os.path.join(dirname, name)
  File "/usr/lib64/python2.5/posixpath.py", line 65, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 5: ordinal not in range(128)
```

**Comment by robmcmullen** [comment]
_[Trac time 20080209 022707Z]_ e93c2da781a8338895f3837819d7baa7fe6f0c78 Fixed #362: changed URL minibuffer to use unicode
