### ISSUE TITLE
dired mode doesn't work with unicode paths

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#364]
_[Trac time 20080208 234117Z]_ Loading a path that contains unicode filenames in dired results in:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy-git/peppy/frame.py", line 256, in newMode
    mode = wrapper.createMajorMode(self.frame, buffer)
  File "/home/rob/src/peppy-git/peppy/major.py", line 97, in createMajorMode
    self.editwin = requested(self.splitter, self, buffer, frame)
  File "/home/rob/src/peppy-git/peppy/dired.py", line 213, in __init__
    self.reset()
  File "/home/rob/src/peppy-git/peppy/dired.py", line 421, in reset
    self.SetStringItem(index, 6, str(key))
  File "/home/rob/src/peppy-git/peppy/vfs/itools/uri/generic.py", line 526, in __str__
    path = str(self.path)
  File "/home/rob/src/peppy-git/peppy/vfs/itools/uri/generic.py", line 257, in __str__
    path += '/'.join([ str(x) for x in self ])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-6: ordinal not in range(128)
```

**Comment by robmcmullen** [comment]
_[Trac time 20080209 022718Z]_ f31e87bb5a1299be92ba7b0ae89e5e1e80f3f685 Fixed #364: changed dired to use unicode when displaying filename
- also fixed BufferList mode for the same reason
