### ISSUE TITLE
Failed to open file with unicode path

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#368]
_[Trac time 20080211 113708Z]_ To tickets #365 and #367

Summary:
If path containing non-latin (for example Cyrillic) characters Peppy can load files with *.py, *.sh, etc. extensions. But when trying to load file with no extension (simple plain-text file) Peppy displays an error message in a buffer. It possible to change (or add) extension (for example - .py) and Peppy opens such file with no errors. If path contain only latin characters no errors occurred.

Error message:

```
raceback (most recent call last):
  File "/home/h8/peppy/trunk/peppy/frame.py", line 698, in open
    buffer = LoadingBuffer(user_url, modecls)
  File "/home/h8/peppy/trunk/peppy/buffers.py", line 570, in __init__
    self.modecls = MajorModeMatcherDriver.match(self)
  File "/home/h8/peppy/trunk/peppy/major.py", line 1225, in match
    mode = cls.attemptOpen(plugins, buffer)
  File "/home/h8/peppy/trunk/peppy/major.py", line 1415, in attemptOpen
    mode = plugin.attemptOpen(buffer)
  File "/home/h8/peppy/trunk/peppy/mainmenu.py", line 1013, in attemptOpen
    refcopy = vfs.get_reference(str(buffer.url))
  File "/home/h8/peppy/trunk/peppy/vfs/itools/uri/generic.py", line 526, in __str__
    path = str(self.path)
  File "/home/h8/peppy/trunk/peppy/vfs/itools/uri/generic.py", line 257, in __str__
    path += '/'.join([ str(x) for x in self ])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
```

PS. It seems that I need a login to Track

Dmitry Stropaloff <helions8 (at) gmail dot com>

**Comment by robmcmullen** [comment]
_[Trac time 20080211 172538Z]_ I can duplicate this bug here, so I'll start working on it.

**Comment by robmcmullen** [comment]
**[comment by helions8]** _[Trac time 20080211 183128Z]_ Replying to [comment:1 rob]:

> I can duplicate this bug here, so I'll start working on it.

Same thing on windows host.

**Comment by robmcmullen** [comment]
_[Trac time 20080212 011805Z]_ In a different but related error, I also see this when loading a unicode file with no extension from the command line:

```
Traceback (most recent call last):
  File "/home/gnutella/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14355, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy-git/peppy/frame.py", line 672, in open
    buffer = BufferList.findBufferByURL(user_url)
  File "/home/rob/src/peppy-git/peppy/buffers.py", line 54, in findBufferByURL
    url = vfs.canonical_reference(url)
  File "/home/rob/src/peppy-git/peppy/vfs/__init__.py", line 42, in canonical_reference
    ref = normalize(unicode(ref))
  File "/home/rob/src/peppy-git/peppy/vfs/itools/uri/generic.py", line 540, in __unicode__
    path = unicode(self.path)
  File "/home/rob/src/peppy-git/peppy/vfs/itools/uri/generic.py", line 268, in __unicode__
    path += u'/'.join([ unicode(x) for x in self ])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 8: ordinal not in range(128)
```

**Comment by robmcmullen** [comment]
_[Trac time 20080212 063301Z]_ b27320d5671efd865afdfbe44a83e6037de00ffa Refs #368: Partial fix for unicode paths with no extension
- recoded vfs.normalize to convert every file:// url to unicode
- recoded all attemptOpen plugin methods to handle unicode paths

**Comment by robmcmullen** [comment]
**[comment by helions8]** _[Trac time 20080212 110352Z]_ Replying to [comment:4 rob]:
b27320d5671efd865afdfbe44a83e6037de00ffa Refs #368: Partial fix for unicode paths with no extension

> - recoded vfs.normalize to convert every file:// url to unicode
> - recoded all attemptOpen plugin methods to handle unicode paths

Now Peppy can load files with no extensions from unicode path, but when attempting to save it fails with message:

```
buffers.py:477 Buffer.save: Failed writing to file:///home/h8/<path_to_file>
```

**Comment by robmcmullen** [comment]
_[Trac time 20080212 134710Z]_ Thanks for the feedback -- I didn't get a chance to fix the code used to save the files, so hopefully I can get to that today.

**Comment by robmcmullen** [comment]
_[Trac time 20080213 013455Z]_ Note: Mistakenly tied to ticket #366 instead of #368
14f710d7a1d2b62396eb33f795904f1586f09595 Refs #366: fixed file reverting for unicode pathnames

**Comment by robmcmullen** [comment]
_[Trac time 20080213 013511Z]_ Note: Mistakenly tied to ticket #366 instead of #368
d7bca508d145cbf9eb4169bed22b35197a74825f Refs #366: Changed vfs to handle both unicode and non-unicode files
- attempt unicode first (will work on all windows systems and all unix systems that have a UTF8 locale)
- if unicode doesn't work, encode to utf-8 and try again
- return values based on the input string type
- write message to status bar when saving file

**Comment by robmcmullen** [comment]
_[Trac time 20080213 013515Z]_ Note: Mistakenly tied to ticket #366 instead of #368
9b4390efb9dd09806d4400c1f91271ee243d1cb7 Refs #366: Fixed LocalFileMinibuffer for unicode paths
- glob.glob doesn't handle unicode when locale is C/POSIX, so handle the encoding/decoding via utf-8

**Comment by robmcmullen** [comment]
_[Trac time 20080214 010628Z]_ 7c0e1605339fbfa18e77f868d559c77c49e2b19a Refs #368: Convert names to unicode in dired mode

**Comment by robmcmullen** [comment]
**[comment by helions8]** _[Trac time 20080214 085347Z]_ It seems that all is working fine now. At least I have no error messages now.

**Comment by robmcmullen** [comment]
_[Trac time 20080218 222846Z]_ I think I'll mark this as fixed since it seems to be working for everybody.
