### ISSUE TITLE
Can't add to empty file cabinet

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#441]
_[Trac time 20080504 013506Z]_ Attempting to add a file to an empty file cabinet results in this exception when trying to display the menu:

```
Traceback (most recent call last):
  File "/home/gnutella/peppy-git/peppy/menu.py", line 550, in OnMenuOpen
    action.updateOnDemand()
  File "/home/gnutella/peppy-git/peppy/actions/__init__.py", line 827, in updateOnDemand
    self.dynamic()
  File "/home/gnutella/peppy-git/peppy/actions/__init__.py", line 459, in dynamic
    if item.GetId()==self.toplevel[0]:
IndexError: list index out of range
```

but if you exit and restart, the item has been added to the list.  It just can't seem to display it the first time.

**Comment by robmcmullen** [comment]
_[Trac time 20080504 013643Z]_ 2d714c6c762e29bd873ae18dee355555a976a887 Fixed #441: check existence of list elements before checking item position in ListAction.dynamic
