### ISSUE TITLE
Text style dialog problem with Style Theme

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#475]
_[Trac time 20080701 205118Z]_ Attempting to change the style theme results in:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy-git/peppy/editra/style_editor.py", line 514, in OnChoice
    self.preview.UpdateAllStyles(val)
  File "/home/rob/src/peppy-git/peppy/editra/stcmixin.py", line 377, in UpdateAllStyles
    self.LoadStyleSheet(self.GetStyleSheet(spec_style), force=True)
AttributeError: 'FundamentalSTC' object has no attribute 'GetStyleSheet'
```

**Comment by robmcmullen** [comment]
_[Trac time 20080703 005339Z]_ 90aaa5f00f5be3dbf12241b848007d4279a5dccd Fixed #474 and #475: synced style editor with Editra svn 54465
- peppy.preferences.changed message moved inside the ID_OK check
- added new themes from Editra
- the "New" style button in the dialog now creates a blank style
- fixed LoadStyleSheet to merge the imported style from a blank style so that everything doesn't always inherit from the built-in defaults
