### ISSUE TITLE
Can't open text style dialog in HTML view mode

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#550]
_[Trac time 20081009 192045Z]_ Attempting to open the text style dialog box when editing about:peppy in HTMLView mode, you get:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14572, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy-git/peppy/plugins/editra_styleeditor.py", line 35, in action
    dlg.OpenPreviewFile(self.mode.editra_lang)
AttributeError: 'HTMLViewMode' object has no attribute 'editra_lang'
```

**Comment by robmcmullen** [comment]
_[Trac time 20081010 010815Z]_ 399b0859edddd20b800d39ffc64fad005e1c0745 Fixed #550: default to python editra language if not a fundamental mode subclass
