### ISSUE TITLE
Get peppy working with out-of-the-box wxPython on Mac OS X 10.5

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#554]
_[Trac time 20081021 042357Z]_ peppy doesn't quite work with the default wxPython on Mac OS X 10.5:

```
Traceback (most recent call last):
 File "peppy.py", line 15, in <module>
   peppy.main.main()
 File "/Users/jstrout/Downloads/peppy-0.8.9/peppy/main.py", line 1057, in main
   run()
 File "/Users/jstrout/Downloads/peppy-0.8.9/peppy/main.py", line 1038, in run
   frame=BufferFrame(peppy.args)
 File "/Users/jstrout/Downloads/peppy-0.8.9/peppy/frame.py", line 393, in __init__
   Left().Layer(10).DockFixed().
AttributeError: 'AuiPaneInfo' object has no attribute 'DockFixed'
```

**Comment by robmcmullen** [comment]
_[Trac time 20081022 004730Z]_ e37d14818142b79c7a40d3d0e809e361bddbb4b8 Fixed #554: because of Mac OS X 10.5, now check to see if the AUI has DockFixed before using it
