### ISSUE TITLE
Can't close last buffer in frame

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#557]
_[Trac time 20081023 210851Z]_ Closing the last tab in a frame using the close icon results in:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14572, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "z:\src\peppy-git\peppy\mainmenu.py", line 417, in action
  File "/home/rob/src/peppy-git/peppy/frame.py", line 440, in closeBuffer
    buffer.removeAllViewsAndDelete()
  File "/home/rob/src/peppy-git/peppy/buffers.py", line 408, in removeAllViewsAndDelete
    viewer.frame.tabs.closeWrapper(viewer)
  File "/home/rob/src/peppy-git/peppy/notebook.py", line 194, in closeWrapper
    buffer = BufferList.findBufferByURL("about:blank")
NameError: global name 'BufferList' is not defined
```

**Comment by robmcmullen** [comment]
_[Trac time 20081024 011104Z]_ 2171f2e23470a27c5221861f0567ed8f04d8649e Fixed #557: added import of peppy.buffers to notebook
