### ISSUE TITLE
File Browser Sidebar problem

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#566]
**[reported by ndelatorre@...]** _[Trac time 20081120 121646Z]_ Im getting this error after clicking on the File Browser on the sidebar. The window of peppy gets unusable.
The version of peppy is 0.8.34 and wxPython 2.8.9.1.

/usr/lib/python2.6/site-packages/peppy/lib/pkg_resources.py:17: DeprecationWarning: the sets module is deprecated
  from sets import ImmutableSet
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14572, in <lambda>
    lambda event: event.callable(_event.args, *_event.kw) )
  File "/usr/lib/python2.6/site-packages/peppy/sidebar.py", line 86, in initPostCallback
    self.createContextMenuEventBindings()
  File "/usr/lib/python2.6/site-packages/peppy/context_menu.py", line 32, in createContextMenuEventBindings
    self.Bind(wx.EVT_CONTEXT_MENU, self.OnContextMenu)
  File "/usr/lib/python2.6/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 3908, in Bind
    event.Bind(self, id, id2, handler)  
  File "/usr/lib/python2.6/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 3982, in Bind
    target.Connect(id1, id2, et, function)
  File "/usr/lib/python2.6/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 3868, in Connect
    return _core_.EvtHandler_Connect(_args, *_kwargs)
TypeError: in method 'EvtHandler_Connect', expected argument 1 of type 'wxEvtHandler *'

**Comment by robmcmullen** [comment]
_[Trac time 20090416 034735Z]_ I can finally duplicate this using a different user ID on my machine here at home.

```
gnutella@hammer:~ $ peppy
*** Wed Apr 15 20:45:01 2009 ***
Traceback (most recent call last):
  File "/home/gnutella/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14355, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.9.12-py2.5.egg/peppy/sidebar.py", line 86, in initPostCallback
    self.createContextMenuEventBindings()
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.9.12-py2.5.egg/peppy/context_menu.py", line 32, in createContextMenuEventBindings
    self.Bind(wx.EVT_CONTEXT_MENU, self.OnContextMenu)
  File "/home/gnutella/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 3869, in Bind
    event.Bind(self, id, id2, handler)
  File "/home/gnutella/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 3906, in Bind
    target.Connect(id1, id2, et, function)
  File "/home/gnutella/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 3829, in Connect
    return _core_.EvtHandler_Connect(*args, **kwargs)
TypeError: in method 'EvtHandler_Connect', expected argument 1 of type 'wxEvtHandler *'
```

**Comment by robmcmullen** [comment]
_[Trac time 20090416 042452Z]_ 10a236239552178540b4f857bbae0a36f19eb669 Fixed #566: in a multiple-inheritance initialization, apparently you need to init the wx component before any other mixins
- Sidebar.**init** was using a wx.CallAfter to initialize the event handlers, but it was being triggered before the wx window had completed its two-phase init.
- this was finally evident when I printed out self: file_browser.py:45 FileBrowser.createContextMenuEventBindings2: <**builtin**.FileBrowser;  > -- there's no mention of the "proxy of <Swig object *xxxxxx>"

**Comment by robmcmullen** [comment]
_[Trac time 20081215 231952Z]_ It looks like you're using Python 2.6.  I actually haven't tried it with 2.6 yet, so maybe there's something different with event handlers?  Not sure yet...

For the moment, I'm still tied to Python 2.5 so I've not been able to test with 2.6 yet.

**Comment by robmcmullen** [comment]
_[Trac time 20090401 180925Z]_ A user on python 2.5 supplied this story and traceback, so it's a problem on python 2.5 as well:

> as i opened FileBrowser, the left mousebutton is static with the menu. means: i can't close peppy or use the left mousebutton. ever i clicked the mouse button, the filebrowser slides out or in. this is unstoppable... i have to kill peppy.
> 
> ```
> Traceback (most recent call last):
>   File
> "/usr/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py",
> line 14572, in <lambda> lambda event: event.callable(*event.args,
> **event.kw) ) File "/usr/lib/python2.5/site-packages/peppy/sidebar.py",
> line 86, in initPostCallback self.createContextMenuEventBindings() File
> "/usr/lib/python2.5/site-packages/peppy/context_menu.py", line 32, in
> createContextMenuEventBindings self.Bind(wx.EVT_CONTEXT_MENU,
> self.OnContextMenu) File
> "/usr/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py",
> line 3908, in Bind event.Bind(self, id, id2, handler) File
> "/usr/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py",
> line 3982, in Bind target.Connect(id1, id2, et, function) File
> "/usr/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py",
> line 3868, in Connect return _core_.EvtHandler_Connect(*args, **kwargs)
> TypeError: in method 'EvtHandler_Connect', expected argument 1 of type
> 'wxEvtHandler *' Killed
> ```
