### ISSUE TITLE
Save As fails if original file is deleted

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#570]
_[Trac time 20081215 235057Z]_ 1. open file
1. remove file on filesystem
1. (click to remove the expected dialog prompting that your work will be lost unless you save the file.)
1. attempt to save as
1. error traceback in console:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14572, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/lib/peppy/mainmenu.py", line 472, in action
  File "/home/rob/lib/peppy/major.py", line 608, in save
  File "/home/rob/lib/peppy/buffers.py", line 526, in save
  File "/home/rob/lib/peppy/vfs/itools/vfs/vfs.py", line 53, in get_permissions
  File "/home/rob/lib/peppy/vfs/itools/vfs/folders.py", line 85, in get_permissions
  File "/home/rob/lib/peppy/vfs/itools/vfs/file.py", line 82, in get_permissions
OSError: [Errno 2] No such file or directory: '/tmp/blah234.txt'
```

**Comment by robmcmullen** [comment]
_[Trac time 20081216 013543Z]_ 09a1e85fe67ca8aba565b76329849f1d81191250 Fixed #570: fixed Save As to skip setting the permissions from the original file if the original file has been deleted
