### ISSUE TITLE
Exporting subset of HSI cube fails

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#586]
_[Trac time 20090202 194846Z]_ 1. create subset of HSI image
1. attempt to save using File -> Export -> as ENVI
1. create filename and hit Save

```
ENVI.py:222 export: writing cube to file:///work/tacsat3/1111/subset.POrtho.bil
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14572, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy-git/peppy/hsi/hsi_menu.py", line 468, in action
  File "/work/lib/peppy/hsi/ENVI.py", line 224, in export
    cube.writeRawData(fh, options, progress)
  File "/work/lib/peppy/hsi/cube.py", line 1420, in writeRawData
    for block in iterator:
  File "/work/lib/peppy/hsi/cube.py", line 1361, in iterRaw
    for bytes in interleaveiter(byte_order):
  File "/work/lib/peppy/hsi/cube.py", line 1326, in iterRawBIL
    band = self.cube_io.getFocalPlaneRaw(i, use_progress=False)
AttributeError: 'NoneType' object has no attribute 'getFocalPlaneRaw'
```

**Comment by robmcmullen** [comment]
_[Trac time 20090213 015626Z]_ b46d13b59d96efce8ca2d1802865c63fc77c11a2 Fixed #586: updated subcubes to use the cube_io paradigm
- added SubCubeReader class to be used as cube_io for Subcubes
- SubCubeReader proxies the parent cube's methods to get bands, spectra, etc.
- added CubeReader to list of classes exported by hsi.common
