### ISSUE TITLE
Strange logfile error when running with -d flag

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#608]
_[Trac time 20090416 153029Z]_ Only on my test account when I run `peppy -d` do I see the following traceback whenever a debug print is generated (this particular case occurs when popping up the code explorer sidebar, but anything that generates debug printing will produce a similar error):

```
Traceback (most recent call last):
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.9.14-py2.5.egg/peppy/lib/springtabs.py", line 238, in OnLeftDown
    self.GetParent().setRadio(self)
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.9.14-py2.5.egg/peppy/lib/springtabs.py", line 354, in setRadio
    self.popupItem(item)
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.9.14-py2.5.egg/peppy/lib/springtabs.py", line 364, in popupItem
    dprint("Popping up %s" % item.GetLabel())
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.9.14-py2.5.egg/peppy/debug.py", line 84, in dprint
    writeToLog(dlogfh, str)
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.9.14-py2.5.egg/peppy/debug.py", line 75, in writeToLog
    logfh.write("%s:%d %s%s: %s%s" % (os.path.basename(caller[1]),caller[2],cls,caller[3],text,os.linesep))
IOError: [Errno 0] Error
```

I added some debug printing, and it seems like the file handle is actually open:

```
logfh=<open file '<stderr>', mode 'w' at 0x7f1114356210>
text=Popping up Code Explorer
```

**Comment by robmcmullen** [comment]
_[Trac time 20090416 183404Z]_ e97231d0105e2496e8ef046b945f3e6e3fb6d31f Fixed #608: workaround for the "IOError [Errno 0] Error" problem by using a try/except
