### ISSUE TITLE
Upgrading pyenchant to 1.5.1 breaks py2exe

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#612]
_[Trac time 20090420 223131Z]_ I tried upgrading pyenchant to 1.5.1 and found that it results in py2exe failing to load the module.

```
Traceback (most recent call last):
  File "peppy\lib\stcspellcheck.pyo", line 63, in <module>
  File "enchant\__init__.pyo", line 93, in <module>
  File "enchant\_enchant.pyo", line 61, in <module>
  File "enchant\utils.pyo", line 202, in get_resource_filename
  File "pkg_resources.pyo", line 841, in resource_filename
  File "pkg_resources.pyo", line 1303, in get_resource_filename
NotImplementedError: resource_filename() only supported for .egg, not .zip
```

**Comment by robmcmullen** [comment]
_[Trac time 20090420 223221Z]_ 705d59f6843fc6cd389e224894c9c996194bf26e Refs #612: added debug message when enchant import fails for some unusual reason

**Comment by robmcmullen** [comment]
_[Trac time 20090421 011042Z]_ Looks like it's a problem in [pyenchant itself](https://sourceforge.net/tracker/?func=detail&aid=2776858&group_id=129919&atid=716237)
