### ISSUE TITLE
installing via "easy_install -U peppy" does not result in a working installation.

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#613]
**[reported by joshknox@...]** _[Trac time 20090421 153516Z]_ After install, running "peppy" fails with "ImportError: No module named main".

If I install the source and do "python run.py" that seems to work.

[josh@mothership ~]> sudo easy_install -U peppy
Searching for peppy
Reading http://pypi.python.org/simple/peppy/
Reading http://peppy.flipturn.org/
Reading http://peppy.flipturn.org/archive/
Reading http://www.flipturn.org/peppy/
Reading http://www.flipturn.org/peppy/archive/
Best match: peppy 0.9.27
Downloading http://peppy.flipturn.org/archive/peppy-0.9.27.tar.bz2
Processing peppy-0.9.27.tar.bz2
Running peppy-0.9.27/setup.py -q bdist_egg --dist-dir /tmp/easy_install-HB4MM1/peppy-0.9.27/egg-dist-tmp-8B3S0z
packages = ['peppy', 'peppy.i18n', 'peppy.plugins', 'peppy.actions', 'peppy.vfs', 'peppy.vfs.itools', 'peppy.vfs.itools.uri', 'peppy.vfs.itools.vfs', 'peppy.hsi', 'peppy.lib', 'peppy.yapsy', 'peppy.editra', 'peppy.editra.syntax', 'peppy.editra.eclib']
/usr/lib/python2.5/distutils/dist.py:263: UserWarning: Unknown distribution option: 'windows'
  warnings.warn(msg)
no previously-included directories found matching 'manual/_build'
no previously-included directories found matching 'peppy-*'
build/lib
created build/lib/peppy/iconmap.py
Adding peppy 0.9.27 to easy-install.pth file
Installing peppy script to /usr/bin

Installed /usr/lib/python2.5/site-packages/peppy-0.9.27-py2.5.egg
Processing dependencies for peppy
Finished processing dependencies for peppy

[josh@mothership ~]> peppy
Traceback (most recent call last):
  File "/usr/bin/peppy", line 5, in <module>
    pkg_resources.run_script('peppy==0.9.27', 'peppy')
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 448, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 1166, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.5/site-packages/peppy-0.9.27-py2.5.egg/EGG-INFO/scripts/peppy", line 13, in <module>
    import peppy.main
  File "/usr/bin/peppy.py", line 13, in <module>
    import peppy.main
ImportError: No module named main

**Comment by robmcmullen** [comment]
_[Trac time 20090422 215900Z]_ It looks like it's somehow getting installed as an egg.  I had thought I had set zip_safe to false, so I'll have to check...

**Comment by robmcmullen** [comment]
_[Trac time 20090422 221624Z]_ Oh, I just realized what it is.  It looks like somehow a file named "peppy.py" got stuck in /usr/bin, probably from an earlier installation.  If you remove /usr/bin/peppy.py, the /usr/bin/peppy script will find peppy from the /usr/lib/python2.5/site-packages directory instead of from /usr/bin/peppy.py.

**Comment by robmcmullen** [comment]
**[comment by joshknox@...]** _[Trac time 20090423 184058Z]_ yup, removal of the offending /usr/bin/peppy.py fixed it.

Thanks!

**Comment by robmcmullen** [comment]
_[Trac time 20090423 190216Z]_ Excellent!  I'll close this bug...
