### ISSUE TITLE
Find backward traceback in LineFromPosition

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#622]
_[Trac time 20090428 161901Z]_ Odd bug just turned up when using C-r to find a string.  I think this the first time I'd used the find minibuffer on this file, which may be significant when trying to reproduce this.  The traceback is:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/plugins/find_replace.py", line 834, in OnChar
    self._lastcall(evt, incremental=True)
  File "/home/rob/src/peppy/peppy/plugins/find_replace.py", line 937, in OnFindP
    self.showLine(posn, help)
  File "/home/rob/src/peppy/peppy/plugins/find_replace.py", line 866, in showLine
    line = self.stc.LineFromPosition(pos)
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/stc.py", line 2822, in LineFromPosition
    return _stc.StyledTextCtrl_LineFromPosition(*args, **kwargs)
TypeError: in method 'StyledTextCtrl_LineFromPosition', expected argument 2 of type 'int'
```

**Comment by robmcmullen** [comment]
_[Trac time 20090429 014124Z]_ ba4533167db54907651a2dedf395330534b03298 Fixed #622: fixed reverse interactive search that wasn't checking for invalid search string
