### ISSUE TITLE
FindWildcard causes infinite recursion

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#644]
_[Trac time 20090518 162145Z]_ C-M-S-s causes:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14574, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy-multikey/peppy/actions/minibuffer.py", line 64, in action
    MinibufferAction.action(self, index, multiplier)
  File "/home/rob/src/peppy-multikey/peppy/actions/minibuffer.py", line 48, in action
    self.showMinibuffer(self.mode)
  File "/home/rob/src/peppy-multikey/peppy/actions/minibuffer.py", line 36, in showMinibuffer
    minibuffer = self.minibuffer(mode, self, label=label, initial=initial)
  File "/home/rob/src/peppy-multikey/peppy/actions/minibuffer.py", line 145, in __init__
    self.createWindow(self.panel, **kwargs)
  File "/home/rob/src/peppy-multikey/peppy/plugins/find_replace.py", line 1051, in createWindow
    self.win = FindBar(parent, self.mode.frame, self.mode, self.search_storage, direction=self.action.find_direction, service=self.action.find_service)
  File "/home/rob/src/peppy-multikey/peppy/plugins/find_replace.py", line 792, in __init__
    self.repeatLastUserInput()
  File "/home/rob/src/peppy-multikey/peppy/plugins/find_replace.py", line 945, in repeatLastUserInput
    self.service.unserialize(self.storage)
  File "/home/rob/src/peppy-multikey/peppy/plugins/find_replace.py", line 82, in unserialize
    self.setFindString(self.settings.find_user)
  File "/home/rob/src/peppy-multikey/peppy/plugins/find_replace.py", line 138, in setFindString
    self.setFlags()
  File "/home/rob/src/peppy-multikey/peppy/plugins/find_replace.py", line 449, in setFlags
    self.flags = self.getFlags(wx.stc.STC_FIND_REGEXP)
  File "/home/rob/src/peppy-multikey/peppy/plugins/find_replace.py", line 109, in getFlags
    self.setFlags()

...

  File "/home/rob/src/peppy-multikey/peppy/plugins/find_replace.py", line 449, in setFlags
    self.flags = self.getFlags(wx.stc.STC_FIND_REGEXP)
RuntimeError: maximum recursion depth exceeded
```

**Comment by robmcmullen** [comment]
_[Trac time 20090518 175837Z]_ [old svn rev2014] Fixed #644: changed getFlags to only call setFlags if a setting has changed
