### ISSUE TITLE
Crashes on tab change

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#661]
_[Trac time 20090521 000614Z]_ Trying to open a new tab results in:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy-multikey/peppy/main.py", line 461, in OnIdle
    top.processIdleEvent()
  File "/home/rob/src/peppy-multikey/peppy/frame.py", line 342, in processIdleEvent
    self.root_accel.forceToolbarUpdate()
  File "/home/rob/src/peppy-multikey/peppy/menu.py", line 469, in forceToolbarUpdate
    action.showEnable()
  File "/home/rob/src/peppy-multikey/peppy/actions/__init__.py", line 333, in showEnable
    state = self.isEnabled()
  File "/home/rob/src/peppy-multikey/peppy/actions/base.py", line 31, in isEnabled
    return not self.mode.buffer.busy and self.isActionAvailable()
  File "/home/rob/src/peppy-multikey/peppy/mainmenu.py", line 652, in isActionAvailable
    return self.mode.CanUndo()
AttributeError: 'BlankMode' object has no attribute 'CanUndo'
```

This must be a new regression because it didn't happen this morning.

**Comment by robmcmullen** [comment]
_[Trac time 20090521 001021Z]_ [old svn rev2045] Fixed #661: fixed regression introduced by 996bc3fe1fc4b44d2f15fa69ff43e071787b2ba73
- MajorMode.**init** now creates a class cache for each different class
- my naive initial attempt put the class cache in the class attributes of MajorMode itself, but that meant that all subclasses saw the same cache.  Not at all what was intended
