### ISSUE TITLE
Closing last window raises error

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#667]
_[Trac time 20090527 233845Z]_ Closing the last window raises:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy-multikey/peppy/frame.py", line 400, in OnClose
    self.closeWindow()
  File "/home/rob/src/peppy-multikey/peppy/frame.py", line 466, in closeWindow
    WindowList.remove(self)
  File "/home/rob/src/peppy-multikey/peppy/actions/__init__.py", line 921, in remove
    cls.storage.remove(item)
ValueError: list.remove(x): x not in list
```

**Comment by robmcmullen** [comment]
_[Trac time 20090527 235114Z]_ [old svn rev2064] Fixed #667: canCloseWindow should have returned result of Peppy.quit()
