### ISSUE TITLE
Can't load files on non-default windows drives

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#67]
_[Trac time 20070105 134916Z]_ peppy is started from the c: drive; trying to load from another drive fails with this:

```
Traceback (most recent call last):
  File "c:Documents and SettingsmcmullenrMy Documentsmcmullenrworkpeppymenudev.py", line 628, in callback
    self.command.run(self.frame.getState(),self.listpos)
  File "c:Documents and SettingsmcmullenrMy Documentsmcmullenrworkpeppymenudev.py", line 40, in run
    self.action(state,pos)
  File "peppy.py", line 87, in action
    self.frame.openFileDialog()
  File "c:Documents and SettingsmcmullenrMy Documentsmcmullenrworkpeppyuffers.py", line 422, in openFileDialog
    self.open(path)
  File "c:Documents and SettingsmcmullenrMy Documentsmcmullenrworkpeppyuffers.py", line 397, in open
    buffer=Buffer(filename,stcparent=self.app.dummyframe,defaultviewer=viewer)
  File "c:Documents and SettingsmcmullenrMy Documentsmcmullenrworkpeppyuffers.py", line 119, in __init__
    self.open(stcparent)
  File "c:Documents and SettingsmcmullenrMy Documentsmcmullenrworkpeppyuffers.py", line 184, in open
    filter.read(self.stc)
  File "c:Documents and SettingsmcmullenrMy Documentsmcmullenrworkpeppyiofilter.py", line 196, in read
    self.fh=self.filter.read(self.protocol,self.urlinfo,stc)
  File "c:Documents and SettingsmcmullenrMy Documentsmcmullenrworkpeppyiofilter.py", line 144, in read
    fh=protocol.getReader(urlinfo)
  File "c:Documents and SettingsmcmullenrMy Documentsmcmullenrworkpeppyiofilter.py", line 67, in getReader
    fh=open(urlinfo.filename,"rb")
IOError: [Errno 2] No such file or directory: '\win32dev\include\pthread.h'
```

**Comment by robmcmullen** [comment]
_[Trac time 20070106 013326Z]_ Fixed by 18ce97f8d35fef8f2b56be52d68660e1e9178c06.
