### ISSUE TITLE
New file fails at backupCallback

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#671]
_[Trac time 20090531 123928Z]_ The backupCallback method is called for a new file, which fails to copy to a backup file because it doesn't exist.  Should check for this instead of raising the exception:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14574, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy-multikey/peppy/buffers.py", line 639, in backupCallback
    vfs.copy(self.url, temp_url)
  File "/home/rob/src/peppy-multikey/peppy/vfs/itools/vfs/vfs.py", line 97, in copy
    return cwd.copy(source, target)
  File "/home/rob/src/peppy-multikey/peppy/vfs/itools/vfs/folders.py", line 182, in copy
    raise OSError
OSError
```

**Comment by robmcmullen** [comment]
_[Trac time 20090531 151842Z]_ [old svn rev2068] Fixed #671: added check for new file in backupCallback
