### ISSUE TITLE
BufferListMode can't delete itself

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#674]
_[Trac time 20090531 184317Z]_ Looks like I left a reference to an old interface:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy-multikey/peppy/lib/multikey.py", line 1069, in OnKeyDown
    processed = self.processMultiKey(evt, keystroke)
  File "/home/rob/src/peppy-multikey/peppy/lib/multikey.py", line 1176, in processMultiKey
    action.actionKeystroke(evt, multiplier=self.entry.repeat_value)
  File "/home/rob/src/peppy-multikey/peppy/actions/__init__.py", line 340, in actionKeystroke
    self.action(0, multiplier)
  File "/home/rob/src/peppy-multikey/peppy/plugins/buffer_list_mode.py", line 130, in action
    self.mode.execute()
  File "/home/rob/src/peppy-multikey/peppy/plugins/buffer_list_mode.py", line 287, in execute
    self.deletePreHook()
AttributeError: 'BufferListMode' object has no attribute 'deletePreHook'
```

**Comment by robmcmullen** [comment]
_[Trac time 20090531 193159Z]_ [old svn rev2078] Fixed #674: removed old deletePreHook call from old Buffer interface
