### ISSUE TITLE
revert about:keybindings fails

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#690]
_[Trac time 20090609 195428Z]_ ```
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14574, in <lambda>
    lambda event: event.callable(_event.args, *_event.kw) )
  File "/home/rob/src/peppy/peppy/mainmenu.py", line 503, in action
    self.mode.buffer.revert()
  File "/home/rob/src/peppy/peppy/buffers.py", line 508, in revert
    self.stc.revertEncoding(self, url=alternate_url, encoding=encoding, allow_undo=allow_undo)
TypeError: revertEncoding() got an unexpected keyword argument 'url'

```
```

**Comment by robmcmullen** [comment]
_[Trac time 20090609 200857Z]_ 66e373d99cd577f23a7815b1dd098b62adc86cf9 Fixed #690: fixed revertEncoding in stcinterface to use updated method signature
- added revertEncoding and revertPostHook to keybinding mode
