### ISSUE TITLE
Refresh broken in dired mode

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#711]
_[Trac time 20090618 153339Z]_ F5 doesn't work to refresh:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14574, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy/peppy/dired_menu.py", line 25, in action
    self.mode.resetList(sort=True)
  File "/home/rob/src/peppy/peppy/dired.py", line 341, in resetList
    self.SortListItems()
AttributeError: 'DiredMode' object has no attribute 'SortListItems'
```

**Comment by robmcmullen** [comment]
_[Trac time 20090618 154150Z]_ fd53a03098c59b1da9ce45ef779063e765b70798 Fixed #711: forgot to update Dired.resetList to change call to SortListItems due to parent window change
- DiredMode is descended from ListMode, and ListMode is now encased in a panel rather than directly inheriting from wx.List
