### ISSUE TITLE
Erasing entire line in Find URL minibuffer raises exception

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#712]
_[Trac time 20090623 190728Z]_ ```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/lib/textctrl_autocomplete.py", line 388, in OnText
    self.processText(text)
  File "/home/rob/src/peppy/peppy/lib/textctrl_autocomplete.py", line 395, in processText
    self._entryCallback()
  File "/home/rob/src/peppy/peppy/mainmenu.py", line 284, in setDynamicChoices
    CompletionMinibuffer.setDynamicChoices(self)
  File "/home/rob/src/peppy/peppy/actions/minibuffer.py", line 515, in setDynamicChoices
    choices = self.complete(text)
  File "/home/rob/src/peppy/peppy/mainmenu.py", line 335, in complete
    self.dprint("uri=%s text=%s path=%s" % (str(uri), text, path))
  File "/home/rob/src/peppy/peppy/vfs/itools/uri/generic.py", line 557, in __str__
    query = encode_query(self.query)
  File "/home/rob/src/peppy/peppy/vfs/itools/uri/generic.py", line 477, in encode_query
    for key, value in query.items():
AttributeError: 'NoneType' object has no attribute 'items'

```
```

**Comment by robmcmullen** [comment]
_[Trac time 20090623 192803Z]_ 44d67bb472b3b674cd0e5d432fd8b5cf33734323 Fixed #712: added special case check for query string
- EmptyReference uses the value 'None' for the query string, and encode_query couldn't handle that before this fix
- updated test case
