### ISSUE TITLE
i18n language selection problem on SUSE linux

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#749]
_[Trac time 20090815 161111Z]_ Hi,
when trying to change the peppy language to german, the following error
occured: (please continue reading after the Error Msg)

```
#---- Notes ----#
Please provide additional information about the crash here


#---- System Information ----#
Peppy Version: 0.10.0
Operating System: Linux 2.6.27.19-3.2-pae i686
Python Version: 2.6 (44cf51f32d93c3ee1b615702133bebecec240020:66714, Feb  3 2009, 20:52:03)
[GCC 4.3.2 [gcc-4_3-branch revision 141291]]
wxPython Version: 2.8.8.1 (gtk2-unicode)
wxPython Info: (__WXGTK__, wxGTK, unicode, gtk2, wx-assertions-off,
SWIG-1.3.29)
Python Encoding: Default=ascii  File=UTF-8
wxPython Encoding: latin1
System Architecture: 32bit i686
Byte order: little
Frozen: False
#---- End System Information ----#

#---- Traceback Info ----#
*** Sat Aug 15 14:06:02 2009 ***
Traceback (most recent call last):
 File "/usr/lib/python2.6/site-packages/wx-2.8-gtk2-unicode/wx/_core.py",
line 14551, in <lambda>
   lambda event: event.callable(*event.args, **event.kw) )
 File "/usr/local/lib/python2.6/site-packages/peppy/plugins/preferences.py",
line 49, in action
   self.showDialog()
 File "/usr/local/lib/python2.6/site-packages/peppy/plugins/preferences.py",
line 38, in showDialog
   locals = dlg.applyPreferences()
 File "/usr/local/lib/python2.6/site-packages/peppy/lib/userparams.py", line
2178, in applyPreferences
   page_locals = page.applyPreferences()
 File "/usr/local/lib/python2.6/site-packages/peppy/lib/userparams.py", line
2040, in applyPreferences
   locals = pref.update()
 File "/usr/local/lib/python2.6/site-packages/peppy/lib/userparams.py", line
1844, in update
   val = param.getValue(ctrl)
 File "/usr/local/lib/python2.6/site-packages/peppy/main.py", line 199, in
getValue
   return ctrl.getCatalog()
 File "/usr/local/lib/python2.6/site-packages/peppy/i18n/__init__.py", line
159, in getCatalog
   return description_map[self.GetValue()]
KeyError: u'Default: German'


*** Sat Aug 15 14:07:07 2009 ***
Traceback (most recent call last):
 File "/usr/lib/python2.6/site-packages/wx-2.8-gtk2-unicode/wx/_core.py",
line 14551, in <lambda>
   lambda event: event.callable(*event.args, **event.kw) )
 File "/usr/local/lib/python2.6/site-packages/peppy/plugins/preferences.py",
line 49, in action
   self.showDialog()
 File "/usr/local/lib/python2.6/site-packages/peppy/plugins/preferences.py",
line 38, in showDialog
   locals = dlg.applyPreferences()
 File "/usr/local/lib/python2.6/site-packages/peppy/lib/userparams.py", line
2178, in applyPreferences
   page_locals = page.applyPreferences()
 File "/usr/local/lib/python2.6/site-packages/peppy/lib/userparams.py", line
2040, in applyPreferences
   locals = pref.update()
 File "/usr/local/lib/python2.6/site-packages/peppy/lib/userparams.py", line
1844, in update
   val = param.getValue(ctrl)
 File "/usr/local/lib/python2.6/site-packages/peppy/main.py", line 199, in
getValue
   return ctrl.getCatalog()
 File "/usr/local/lib/python2.6/site-packages/peppy/i18n/__init__.py", line
159, in getCatalog
   return description_map[self.GetValue()]
KeyError: u'Default: German'

#---- End Traceback Info ----#
```

Apparently, the error occurs because of the entry in the language field (is
this SuSE-specific???)  which is "Default: German"

**Comment by robmcmullen** [comment]
_[Trac time 20090817 014414Z]_ 8c0792f62aaabf45e0ee58dfa298f324f15e24d2 Refs #749: attempted workaround for language that appears as "Default: German"

**Comment by robmcmullen** [comment]
_[Trac time 20090817 015820Z]_ Marking as fixed after feedback from original poster.
