### ISSUE TITLE
opening filename with unicode characters fails

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#750]
_[Trac time 20090818 173321Z]_ ```
Failed opening file:///home/test/abc_???.txt.

Detailed error message follows:

Traceback (most recent call last):
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.11.0-py2.5.egg/peppy/fileopener.py", line 174, in determineMajorMode
    self.scanBufferForMajorMode()
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.11.0-py2.5.egg/peppy/fileopener.py", line 197, in scanBufferForMajorMode
    self.modecls = MajorModeMatcherDriver.match(self.buffer, url=self.url)
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.11.0-py2.5.egg/peppy/majormodematcher.py", line 194, in match
    cls.dprint("%s: metadata=%s" % (str(url), str(metadata)))
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.11.0-py2.5.egg/peppy/vfs/itools/uri/generic.py", line 559, in **str**
    path = str(self.path)
  File "/home/gnutella/lib/python2.5/site-packages/peppy-0.11.0-py2.5.egg/peppy/vfs/itools/uri/generic.py", line 264, in **str**
    path += '/'.join([ str(x) for x in self ])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-6: ordinal not in range(128)

```
```

**Comment by robmcmullen** [comment]
_[Trac time 20090819 200534Z]_ 4fd7b9f1011a896cdc7f9d0adf3ca7e4bcfa14e9 Fixed #750: need to remember to use unicode() rather than str() when printing all URLs
