### ISSUE TITLE
Looking up non-existent tag fails

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#753]
_[Trac time 20090819 200939Z]_ Using C-c C-t to lookup a tag from the CTAGS, if you enter a tag in the list that doesn't exist, you get the error:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14574, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy/peppy/actions/minibuffer.py", line 290, in performAction
    error = self.action.processMinibuffer(self, self.mode, value)
  File "/home/rob/src/peppy/peppy/project/actions.py", line 83, in processMinibuffer
    text = self.mode.project_info.getTagInfo(name)
  File "/home/rob/src/peppy/peppy/project/project.py", line 141, in getTagInfo
    for t in tags:
TypeError: 'NoneType' object is not iterable
```

**Comment by robmcmullen** [comment]
_[Trac time 20091113 154602Z]_ 93a47b83a4d88a7a871abf00d99314a559149206 Fixed #753: added check for unknown tag
