### ISSUE TITLE
Macro error when recording SelectAll followed by Remove Trailing Whitespace

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#756]
_[Trac time 20090820 161833Z]_ One of the two commands is returning:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1381, in OnKeyDown
    processed = self.processMultiKey(evt, keystroke)
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1501, in processMultiKey
    self.doKeystroke(action, evt)
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1306, in doKeystroke
    action.actionKeystroke(evt, multiplier=multiplier)
  File "z:\src\peppy\peppy\actions\__init__.py", line 495, in actionKeystroke
  File "/home/rob/src/peppy/peppy/plugins/macro.py", line 402, in action
    self.stopRecording()
  File "/home/rob/src/peppy/peppy/plugins/macro.py", line 387, in stopRecording
    macro = MacroFS.addMacroFromRecording(recorder, self.mode)
  File "/home/rob/src/peppy/peppy/plugins/macro.py", line 823, in addMacroFromRecording
    macro = PythonScriptableMacro(recorder)
  File "/home/rob/src/peppy/peppy/plugins/macro.py", line 201, in __init__
    data = self.getScriptFromRecorder(recorder)
  File "/home/rob/src/peppy/peppy/plugins/macro.py", line 326, in getScriptFromRecorder
    lines.append(recorded_action.getScripted())
  File "/home/rob/src/peppy/peppy/plugins/macro.py", line 90, in getScripted
    return "%s(frame, mode).action(%d, %d)" % (self.index, self.multiplier)
TypeError: not enough arguments for format string
```

**Comment by robmcmullen** [comment]
_[Trac time 20090820 175007Z]_ f89b9c07a8dc2f2d68a1b908594466c4d6846da7 Fixed #756: fixed bug in RecordedMenuAction
- now outputs the action name which had been accidentally left out
