### ISSUE TITLE
Missing recent file raises exception

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#763]
_[Trac time 20090901 192314Z]_ If attempting to open a recent file and it has been removed, it raises an exception:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/majormodematcher.py", line 185, in match
    metadata = vfs.get_metadata(url)
  File "/home/rob/src/peppy/peppy/vfs/__init__.py", line 178, in get_metadata
    'mtime': fs.get_mtime(ref),
  File "/home/rob/src/peppy/peppy/vfs/itools/vfs/file.py", line 114, in get_mtime
    return datetime.fromtimestamp(cls.unicode_wrapper(reference, getmtime))
  File "/home/rob/src/peppy/peppy/vfs/itools/vfs/file.py", line 40, in unicode_wrapper
    return func(path)
  File "/usr/lib64/python2.5/posixpath.py", line 143, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/work/src/parthenon/tests/sim-reflectance/test1.img'
```

although it does successfully open an empty file of that filename.

**Comment by robmcmullen** [comment]
_[Trac time 20091112 005617Z]_ 5051756b68ea3d45956478e6c82e8a201e308de6 Fixed #763: added check for existence of file before trying to open recent file
