### ISSUE TITLE
Switching mode raises exception

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#770]
_[Trac time 20090924 225829Z]_ Switching from one fundamental mode subclass to another raises an exception:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/stcbase.py", line 1220, in OnModified
    cb(evt)
  File "/home/rob/src/peppy/peppy/fundamental.py", line 834, in spellCheckUpdate
    if self.spell:
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14524, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the FundamentalMode object has been deleted, attribute access no longer allowed.
```

**Comment by robmcmullen** [comment]
_[Trac time 20090924 233038Z]_ 1c64e1f5df373f4c752d228a2bbc22c4d48e40aa Fixed #770: the OnModified event was getting called for both the refstc and the stc used for the gui
- unnecessary to have events on the reference stc, so removed them

**Comment by robmcmullen** [comment]
_[Trac time 20090925 220945Z]_ Just got this exception, but I may have still been on the earlier version.

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/stcbase.py", line 1220, in OnModified
    self.dprint("eol summary: %s" % stats)
  File "/home/rob/src/peppy/peppy/fundamental.py", line 834, in spellCheckUpdate
    if self.spell:
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14524, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the PythonMode object has been deleted, attribute access no longer allowed.
```

It also occurred when I attempted to select a menu item.

**Comment by robmcmullen** [comment]
_[Trac time 20090926 000914Z]_ 04b047299cba6f29ed5a65cb8323308b73adb1c5 Refs #770: corrected error in OnModify callback: should be attached to viewing STC, not reference STC
