### ISSUE TITLE
Setting text selection color fails

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#789]
_[Trac time 20091029 161312Z]_ Updating the select_style in the text styles dialog fails with:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/editra/style_editor.py", line 447, in OnColor
    self.UpdateStyleSet(evt.GetId())
  File "/home/rob/src/peppy/peppy/editra/style_editor.py", line 624, in UpdateStyleSet
    self.preview.RefreshStyles()
  File "/home/rob/src/peppy/peppy/editra/stcmixin.py", line 277, in RefreshStyles
    self.UpdateBaseStyles()
  File "/home/rob/src/peppy/peppy/editra/stcmixin.py", line 326, in UpdateBaseStyles
    self.SetSelBackground(True, sback)
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/stc.py", line 2004, in SetSelBackground
    return _stc.StyledTextCtrl_SetSelBackground(*args, **kwargs)
PyAssertionError: C++ assertion "Ok()" failed at ../src/gtk/colour.cpp(132) in Red(): invalid colour
```

**Comment by robmcmullen** [comment]
_[Trac time 20091029 163228Z]_ 1b983224d1d15849bbef334fb83390983d061b7d Fixed #789: added check to make sure the user has set a background color
- if the background color is empty (meaning that the default background color is being used), the system highlight color will be used
