### ISSUE TITLE
Exception when changing project settings

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#794]
_[Trac time 20091112 012736Z]_ Attempting to change project setting results in:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14614, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy/peppy/project/actions.py", line 323, in action
    self.showProjectPreferences(info)
  File "/home/rob/src/peppy/peppy/project/actions.py", line 276, in showProjectPreferences
    dlg.applyPreferences()
  File "/home/rob/src/peppy/peppy/project/actions.py", line 251, in applyPreferences
    self.local.update()
  File "/home/rob/src/peppy/peppy/lib/userparams.py", line 2777, in update
    param.updateIfModified(self.ctrls, self.orig, self.setValue)
  File "/home/rob/src/peppy/peppy/lib/userparams.py", line 389, in updateIfModified
    setter(self.keyword, val)
  File "/home/rob/src/peppy/peppy/lib/userparams.py", line 2767, in setValue
    setattr(self.obj, keyword, val)
NameError: global name 'val' is not defined
```

**Comment by robmcmullen** [comment]
_[Trac time 20091112 013342Z]_ f3c5cda00f2cd9b6f29073f63eab599f7bf4aec4 Fixed #794: fixed typo in InstancePanel.setValue
