### ISSUE TITLE
tab_wordcompletion fails when unquoted regex character appers in word

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#796]
_[Trac time 20091112 050838Z]_ Attempting to do a word completion on a word that as a regex symbol in it fails.  In this example, tried to complete on `func(self)`:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1381, in OnKeyDown
    processed = self.processMultiKey(evt, keystroke)
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1501, in processMultiKey
    self.doKeystroke(action, evt)
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1306, in doKeystroke
    action.actionKeystroke(evt, multiplier=multiplier)
  File "/home/rob/src/peppy/peppy/actions/__init__.py", line 495, in actionKeystroke
    self.action(0, multiplier)
  File "/home/rob/src/peppy/peppy/plugins/tab_wordcompletion.py", line 156, in action
    if not self.complete():
  File "/home/rob/src/peppy/peppy/plugins/tab_wordcompletion.py", line 142, in complete
    self.c.matches = self.matches(self.matchword(range), range)
  File "/home/rob/src/peppy/peppy/plugins/tab_wordcompletion.py", line 75, in matches
    allmatches = re.findall("\\b" + word + "\\w+", searchtext )
  File "/usr/lib64/python2.5/re.py", line 175, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib64/python2.5/re.py", line 241, in _compile
    raise error, v # invalid expression
error: unbalanced parenthesis
```

**Comment by robmcmullen** [comment]
_[Trac time 20091112 160313Z]_ adefe88f59355a31f386c67ce6bc06413c2835bd Fixed #796: escape word before trying to use re.findall
