### ISSUE TITLE
Regex replacement broken

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#799]
_[Trac time 20091118 203736Z]_ Regex replacement causes:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1262, in OnChar
    self.doKeystroke(action, evt)
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1306, in doKeystroke
    action.actionKeystroke(evt, multiplier=multiplier)
  File "/home/rob/src/peppy/peppy/find_replace/actions.py", line 610, in actionKeystroke
    self.minibuffer.win.OnReplace(None)
  File "/home/rob/src/peppy/peppy/find_replace/actions.py", line 493, in OnReplace
    self.service.doReplace()
  File "/home/rob/src/peppy/peppy/find_replace/services.py", line 787, in doReplace
    self.updateReplacementSelection(orig_start, orig_end, self.stc_equiv_start, self.stc_equiv_pos)
AttributeError: 'FindRegexService' object has no attribute 'updateReplacementSelection'
```

**Comment by robmcmullen** [comment]
_[Trac time 20091118 204934Z]_ a7cc204d289c9766026d74fde24abc304dd18f86 Fixed #799: fixed typo in function name in regex replace service
