### ISSUE TITLE
Replace help raises error

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#800]
_[Trac time 20091118 204324Z]_ Using the "?" key while replacing text raises:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1262, in OnChar
    self.doKeystroke(action, evt)
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1306, in doKeystroke
    action.actionKeystroke(evt, multiplier=multiplier)
  File "/home/rob/src/peppy/peppy/find_replace/actions.py", line 627, in actionKeystroke
    Publisher().sendMessage('peppy.log.info', (self.minibuffer.frame, self.minibuffer.win.__doc__))
AttributeError: 'ReplaceMinibuffer' object has no attribute 'frame'
```

**Comment by robmcmullen** [comment]
_[Trac time 20091118 204938Z]_ f4a43df89029809e3d10929bce5c58bb00209bf1 Fixed #800: fixed incorrect reference to frame in ReplaceBarCommand
