### ISSUE TITLE
enchant crashes

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#822]
_[Trac time 20100128 220728Z]_ From peppy-dev mailing list:

```
#---- Notes ----#
Please provide additional information about the crash here

TRIGGER: Opening a new text file and typing several  characters.


#---- System Information ----#
Peppy Version: svn-devel
Operating System: Linux 2.6.32-4.slh.2-sidux-amd64 x86_64
Python Version: 2.5.4 (9e410e838757228470a098afd8777aed4a122327:67916, Nov 19 2009, 22:14:20)
[GCC 4.3.4]
wxPython Version: 2.8.10.1 (gtk2-unicode)
wxPython Info: (__WXGTK__, wxGTK, unicode, gtk2, wx-assertions-off,
SWIG-1.3.29)
Python Encoding: Default=ascii  File=UTF-8
wxPython Encoding: latin1
System Architecture: 64bit x86_64
Byte order: little
Frozen: False
#---- End System Information ----#

#---- Traceback Info ----#
*** Thu Jan 28 15:15:49 2010 ***
Traceback (most recent call last):
 File "/home/sr/dev/peppy/peppy/main.py", line 506, in OnIdle
   top.processPriorityIdleEvent()
 File "/home/sr/dev/peppy/peppy/frame.py", line 395, in
processPriorityIdleEvent
   mode.idleHandler()
 File "/home/sr/dev/peppy/peppy/major.py", line 1241, in idleHandler
   self.idlePostHook()
 File "/home/sr/dev/peppy/peppy/fundamental.py", line 827, in
idlePostHook
   self.spell.processIdleBlock()
 File "/home/sr/dev/peppy/peppy/lib/stcspellcheck.py", line 438, in
processIdleBlock
   self.processDirtyRanges()
 File "/home/sr/dev/peppy/peppy/lib/stcspellcheck.py", line 588, in
processDirtyRanges
   range_start, range_end = self.processDirtyRange
(self.current_dirty_start, self.current_dirty_end)
 File "/home/sr/dev/peppy/peppy/lib/stcspellcheck.py", line 620, in
processDirtyRange
   self.checkRange(range_start, range_end)
 File "/home/sr/dev/peppy/peppy/lib/stcspellcheck.py", line 329, in
checkRange
   if not spell.check(text[start_index:end_index]):
 File "/usr/lib/pymodules/python2.5/enchant/__init__.py", line 550,
in check
   self._raise_error()
 File "/usr/lib/pymodules/python2.5/enchant/__init__.py", line 524,
in _raise_error
   raise eclass(default)
Error: Unspecified Error

#---- End Traceback Info ----#
```

**Comment by robmcmullen** [comment]
_[Trac time 20100129 023357Z]_ 414e061296c8e61a941fe36f49bf97ce0a6b38fd Fixed #822: workaround for bad enchant library
- added try/except wrapper around call to spell checker in idle time
- if exception, turns off spell checking for that mode and prints debug info
