### ISSUE TITLE
DeprecatedParam returning error

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#824]
_[Trac time 20100208 160650Z]_ Discovered in 0.13.1, it seems that the preferences are trying to check a DeprecatedParam:

```
#---- Notes ----#
First time I used Peppy. Completed editing preferences, saved file and CRASH


#---- System Information ----#
Peppy Version: 0.13.1
Operating System: Linux 2.6.31.12-174.2.3.fc12.i686.PAE i686
Python Version: 2.6.2 (23fa516b9f01b354a07ff082225e4c0b3b57b08d:71600, Aug 21 2009, 12:22:21)
[GCC 4.4.1 20090818 (Red Hat 4.4.1-6)]
wxPython Version: 2.8.10.1 (gtk2-unicode)
wxPython Info: (__WXGTK__, wxGTK, unicode, gtk2, wx-assertions-off, SWIG-1.3.29)
Python Encoding: Default=ascii  File=UTF-8
wxPython Encoding: latin1
System Architecture: 32bit i686
Byte order: little
Frozen: False
#---- End System Information ----#

#---- Traceback Info ----#
*** Mon Feb  8 06:51:17 2010 ***
Traceback (most recent call last):
 File "/usr/lib/python2.6/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14610, in <lambda>
   lambda event: event.callable(*event.args, **event.kw) )
 File "/usr/lib/python2.6/site-packages/peppy/plugins/preferences.py", line 49, in action
   self.showDialog()
 File "/usr/lib/python2.6/site-packages/peppy/plugins/preferences.py", line 38, in showDialog
   locals = dlg.applyPreferences()
 File "/usr/lib/python2.6/site-packages/peppy/lib/userparams.py", line 3062, in applyPreferences
   page_locals = page.applyPreferences()
 File "/usr/lib/python2.6/site-packages/peppy/plugins/preferences.py", line 90, in applyPreferences
   PluginPage.applyPreferences(self)
 File "/usr/lib/python2.6/site-packages/peppy/lib/pluginmanager.py", line 304, in applyPreferences
   pref.update()
 File "/usr/lib/python2.6/site-packages/peppy/lib/userparams.py", line 2732, in update
   param.updateIfModified(self.ctrls, self.orig, setter, locals)
 File "/usr/lib/python2.6/site-packages/peppy/lib/userparams.py", line 386, in updateIfModified
   val = self.getValue(ctrl)
 File "/usr/lib/python2.6/site-packages/peppy/lib/userparams.py", line 599, in getValue
   return str(ctrl.GetValue())
AttributeError: GenStaticText object has no attribute GetValue

#---- End Traceback Info ----#
```

**Comment by robmcmullen** [comment]
_[Trac time 20100208 160918Z]_ 6317e02c7603c8f4f7f323028818a2f368fa4054 Fixed #824: added getValue to DeprecatedParam to allow the updateIfModified to correctly conclude that no change has occurred in the param
