### ISSUE TITLE
Perspective saving fails on unicode URIs

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#830]
_[Trac time 20100210 181637Z]_ Unicode filenames cause an exception in the MajorModeLayout perspective saving.

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/major.py", line 398, in perspectiveChanged
    self.updateLayout()
  File "/home/rob/src/peppy/peppy/major.py", line 403, in updateLayout
    MajorModeLayout.updateLayout(self.editwin.keyword, self.editwin.buffer.url, layout)
  File "/home/rob/src/peppy/peppy/major.py", line 138, in updateLayoutSubsequent
    cls.layout[major_mode_keyword][str(url)] = perspective
  File "/home/rob/src/peppy/peppy/vfs/itools/uri/generic.py", line 559, in __str__
    path = str(self.path)
  File "/home/rob/src/peppy/peppy/vfs/itools/uri/generic.py", line 264, in __str__
    path += '/'.join([ str(x) for x in self ])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-8: ordinal not in range(128)
```

**Comment by robmcmullen** [comment]
_[Trac time 20100210 214447Z]_ 367f9cf2f514f21a0bf61a0eae519b4412dfed9b Fixed #830: changed to unicode when converting URLs to be used as the dict key

**Comment by robmcmullen** [comment]
_[Trac time 20100210 214450Z]_ 4e3454e9beed6a2bf2dacb218db783bfe75b09e0 Refs #830: fixed error in unicode conversion if major mode keyword doesn't exist

**Comment by robmcmullen** [comment]
_[Trac time 20100222 234105Z]_ 82cadc0259af62e12f609221a12afb4db898cba4 Refs #830: fixed url encoding when unicode is same as string
- string matches unicode when used as keyword to dict
- make sure unicode and string aren't the same before deleting string from layout dict
