### ISSUE TITLE
Exporting HSI image as ENVI fails

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#832]
_[Trac time 20100226 181151Z]_ When not specifying a specific endianness when exporting to an ENVI image, it fails with: 

```
Traceback (most recent call last):
  File "/opt/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14614, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy/peppy/hsi/hsi_menu.py", line 471, in action
    handler.export(filename, self.mode.cube, options=options, progress=self.updateProgress)
UnboundLocalError: local variable 'options' referenced before assignment
```

**Comment by robmcmullen** [comment]
_[Trac time 20100226 181258Z]_ 243a1ac4bef98113e28a4c52f0495304da0962bd Fixed #832: missing definition of options dict when endianness not specified
