### ISSUE TITLE
replace all raises exception

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#833]
_[Trac time 20100303 202838Z]_ Using the "!" character to replace all raises:

```
Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1262, in OnChar
    self.doKeystroke(action, evt)
  File "/home/rob/src/peppy/peppy/lib/multikey.py", line 1306, in doKeystroke
    action.actionKeystroke(evt, multiplier=multiplier)
  File "/home/rob/src/peppy/peppy/find_replace/actions.py", line 621, in actionKeystroke
    self.minibuffer.win.OnReplaceAll(None)
  File "/home/rob/src/peppy/peppy/find_replace/actions.py", line 517, in OnReplaceAll
    while not self.service.isWrapped() and valid:
AttributeError: 'FindService' object has no attribute 'isWrapped'
```

**Comment by robmcmullen** [comment]
_[Trac time 20100321 164848Z]_ b0d39f6c9b4bf9c529e80e6f2fd4cbf95521b5d6 Fixed #833: addid isWrapped method to FindService
- fixed cursor position after replace all
