### ISSUE TITLE
Rebuild tag file yields exception

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#836]
_[Trac time 20100318 174312Z]_ Attempting to rebuild the tag file in the peppy source project results in

```
Traceback (most recent call last):
  File "/opt/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14614, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/rob/src/peppy/peppy/project/actions.py", line 100, in action
    info.regenerateTags()
  File "/home/rob/src/peppy/peppy/project/project.py", line 92, in regenerateTags
    ProcessManager().run(cmd, cwd, output)
  File "/home/rob/src/peppy/peppy/lib/processmanager.py", line 262, in run
    Publisher().sendMessage('peppy.processmanager.started', job)
  File "/opt/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/lib/pubsub.py", line 811, in sendMessage
    self.__topicTree.sendMessage(aTopic, message, onTopicNeverCreated)
  File "/opt/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/lib/pubsub.py", line 498, in sendMessage
    deliveryCount += node.sendMessage(message)
  File "/opt/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/lib/pubsub.py", line 336, in sendMessage
    listener(message)
  File "/home/rob/src/peppy/peppy/lib/processmanager.py", line 332, in msgStarted
    self.reset()
  File "/opt/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14564, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the ProcessSidebar object has been deleted, attribute access no longer allowed.
```

**Comment by robmcmullen** [comment]
_[Trac time 20100318 174925Z]_ Hmmm, can't duplicate reliably.  Since it's the dreaded "PyDeadObjectError", I'm assuming that it's the result of the use of the old pubsub.
