### ISSUE TITLE
Job control process not killed when closing window

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#843]
_[Trac time 20100517 231154Z]_ Closing the window (or tab) that contains a running job should prompt with a dialog to kill the running process.  Currently, the process continues and brings up an error:

```
Traceback (most recent call last):
  File "/opt/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14614, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/data2/home/rob/src/peppy/peppy/sidebar.py", line 180, in finishedCallback
    self.finishCallback(job)
  File "z:\src\peppy\peppy\jobcontrol.py", line 266, in deregisterProcess
AttributeError: process
```

Reproduce by opening a second frame, starting the interpreter using Tools -> Run, and then closing the frame that is running the interpreter.

**Comment by robmcmullen** [comment]
_[Trac time 20100610 223244Z]_ But, should it?  Is the process attached to the document or the window?  Should any other tabs containing the same document also show that the process is running?
