### ISSUE TITLE
peppy crashes when title buffer fails to load

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#847]
_[Trac time 20100604 221324Z]_ If the title buffer URL gets corrupted somehow, application startup will fail with:

```
Traceback (most recent call last):
  File "/opt/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14614, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/data2/home/rob/src/peppy/peppy/frame.py", line 571, in titleBuffer
    self.open(wx.GetApp().classprefs.title_page)
  File "/data2/home/rob/src/peppy/peppy/frame.py", line 638, in open
    opener = FileOpener(self, *args, **kwargs)
  File "/data2/home/rob/src/peppy/peppy/fileopener.py", line 74, in __init__
    if 'mode' in self.url.query:
TypeError: argument of type 'NoneType' is not iterable
```

Probably can only be fixed by changing buffer load process to first create tab and then attempt to load the specified URL.

**Comment by robmcmullen** [comment]
_[Trac time 20100604 233918Z]_ d214ff1744f6a13237853846062be7702ad097ef Fixed #847: added error handler to handle failure when decoding a URL
- reorganized FileOpener to automatically call open()
