### ISSUE TITLE
Crash on shutdown when minibuffer is open

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#850]
_[Trac time 20100609 123032Z]_ When any minibuffer is open during attempted shutdown, this is raised:

```
Traceback (most recent call last):
  File "/data2/home/rob/src/peppy/peppy/major.py", line 1245, in OnFocus
    self.frame.spring.clearRadio()
  File "/opt/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14564, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the SpringTabs object has been deleted, attribute access no longer allowed.
```

**Comment by robmcmullen** [comment]
_[Trac time 20100610 225806Z]_ df08ace7e45208aa8ac1fa9502266e36d825166f Fixed #850: added try/catch wrapper for PyDeadObjectError
