### ISSUE TITLE
search in files fails when symlink points to non-existent file

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#867]
_[Trac time 20101030 154347Z]_ Need to add more checks around file open to make sure that a non-existent file doesn't kill the search.

```
search_in_files.py:578 SearchThread.run: Traceback (most recent call last):
  File "/home/rob/src/peppy/peppy/plugins/search_in_files.py", line 563, in run
    gen = method.getMatchGenerator(item, self.matcher)
  File "/home/rob/src/peppy/peppy/plugins/search_in_files.py", line 102, in getMatchGenerator
    fh = open(url, "rb")
IOError: [Errno 2] No such file or directory: u'/home/rob/.mozilla/firefox/o6miawt1.default/lock'
```

occurs because the file `lock` points to a file that doesn't exist.

**Comment by robmcmullen** [comment]
_[Trac time 20101031 163437Z]_ 8a53ddc819dd15ee64c807b32a1cf51bc80f8754 Fixed #867: added try/catch around file opening in getMatchGenerator
