### ISSUE TITLE
error on opening utf-8 files containing characters with values beyond 0x7f

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#872]
**[reported by alefcant@...]** _[Trac time 20110111 113114Z]_ any utf file with BOM or containing characters such à,è, etc. cause the following error:

Traceback (most recent call last):
  File "~/peppy-0.15.0/peppy/fileopener.py", line 176, in determineMajorMode
    self.scanBufferForMajorMode()
  File "~/peppy-0.15.0/peppy/fileopener.py", line 199, in scanBufferForMajorMode
    self.modecls = MajorModeMatcherDriver.match(self.buffer, url=self.url)
  File "~/peppy-0.15.0/peppy/majormodematcher.py", line 192, in match
    mode = cls.matchFile(buffer, magic_size, url, header)
  File "~/peppy-0.15.0/peppy/majormodematcher.py", line 273, in matchFile
    likely = cls.scanLanguage(header, modes)
  File "~/peppy-0.15.0/peppy/majormodematcher.py", line 532, in scanLanguage
    how_likely = mode.verifyLanguage(header)
  File "~/peppy-0.15.0/peppy/fundamental.py", line 237, in verifyLanguage
    if line.startswith(cls.start_line_comment):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
## e.g.
# !/usr/bin/env python
# -_\- coding: utf-8 -_-
## print("è")

BTW I'm downloading the sources via svn to check if the problem is still there

**Comment by robmcmullen** [comment]
_[Trac time 20110111 230159Z]_ svn should handle it better, but if the file indicates UTF-8 and it's actually stored in a different encoding it fails with a similar error.  That's what happens if I try to cut and paste your example:

```
Failed opening file:///tmp/utf8test.txt.

Detailed error message follows:

Traceback (most recent call last):
  File "/data2/home/rob/src/peppy/peppy/fileopener.py", line 183, in determineMajorMode
    self.scanBufferForMajorMode()
  File "/data2/home/rob/src/peppy/peppy/fileopener.py", line 206, in scanBufferForMajorMode
    self.modecls = MajorModeMatcherDriver.match(self.buffer, url=self.url)
  File "/data2/home/rob/src/peppy/peppy/majormodematcher.py", line 192, in match
    mode = cls.matchFile(buffer, magic_size, url, header)
  File "/data2/home/rob/src/peppy/peppy/majormodematcher.py", line 273, in matchFile
    likely = cls.scanLanguage(header, modes)
  File "/data2/home/rob/src/peppy/peppy/majormodematcher.py", line 533, in scanLanguage
    header = encodedBytesToUnicode(header, encoding, bom)
  File "/data2/home/rob/src/peppy/peppy/lib/textutil.py", line 108, in encodedBytesToUnicode
    unicodestring = bytes[start:].decode(encoding)
  File "/opt/lib/python2.5/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 54-56: invalid data
```

So it somehow needs to be able to fall back to some default encoding if the specified encoding fails.
