### ISSUE TITLE
Changing from hexedit mode sometimes crashes

### ISSUE THREAD

**Issue by robmcmullen** [robmcmullen/peppy#99]
_[Trac time 20070209 235656Z]_ Changing from hexedit mode sometimes crashes because it looks like the PyGridCellEditor is trying to destroy a widget that's already destroyed?  GDB traceback:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread -1212377408 (LWP 25204)]
0xb759b52a in wxWindowBase::SendDestroyEvent () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
(gdb) where
#0  0xb759b52a in wxWindowBase::SendDestroyEvent () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#1  0xb7484160 in wxWindow::~wxWindow () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#2  0xb751aa68 in wxControlBase::~wxControlBase () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#3  0xb74fca5a in wxTextCtrl::~wxTextCtrl () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#4  0xb759c10f in wxWindowBase::PopEventHandler () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#5  0xb76e6671 in wxGridCellEditor::Destroy () from /opt/wx/current/lib/libwx_gtk2_adv-2.8.so.0
#6  0xb76e6820 in wxGridCellEditor::~wxGridCellEditor () from /opt/wx/current/lib/libwx_gtk2_adv-2.8.so.0
#7  0xb55bca34 in wxPyGridCellEditor::~wxPyGridCellEditor () from /usr/lib/python2.4/site-packages/wx-2.8-gtk2-ansi/wx/_grid.so
#8  0xb76edc49 in wxGridTypeRegistry::~wxGridTypeRegistry () from /opt/wx/current/lib/libwx_gtk2_adv-2.8.so.0
#9  0xb76f2a78 in wxGrid::~wxGrid () from /opt/wx/current/lib/libwx_gtk2_adv-2.8.so.0
#10 0xb759b786 in wxWindowBase::DestroyChildren () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#11 0xb7484192 in wxWindow::~wxWindow () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#12 0xb75c885d in wxPanel::~wxPanel () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#13 0xb759b786 in wxWindowBase::DestroyChildren () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#14 0xb7484192 in wxWindow::~wxWindow () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#15 0xb75c885d in wxPanel::~wxPanel () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#16 0xb759b625 in wxWindowBase::Destroy () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#17 0xb7482db4 in wxWindow::Destroy () from /opt/wx/current/lib/libwx_gtk2_core-2.8.so.0
#18 0xb794ff7d in _wrap_Window_Destroy () from /usr/lib/python2.4/site-packages/wx-2.8-gtk2-ansi/wx/_core_.so
#19 0xb7e31b9e in PyCFunction_Call () from /usr/lib/libpython2.4.so.1.0
```

So, do I have to destroy the pygridcelleditor's text ctrl in advance, somehow?

**Comment by robmcmullen** [comment]
_[Trac time 20070211 183103Z]_ Fixed in 8e89b135cec0ceedb232ea6eb7ee702b7f48666c.  Whew!  Tough to track that one down -- forgetting to add the event handler that was passed through to the HexCellEditor.Create method was the culprit.
